"""empty message

Revision ID: 28071936d355
Revises: 45c8fb782235
Create Date: 2021-10-16 13:54:01.247129

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '28071936d355'
down_revision = '45c8fb782235'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pasien', 'username')
    op.drop_column('pasien', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pasien', sa.Column('password', mysql.TEXT(), nullable=True))
    op.add_column('pasien', sa.Column('username', mysql.VARCHAR(length=20), nullable=True))
    # ### end Alembic commands ###
