"""empty message

Revision ID: 45c8fb782235
Revises: fc4978528b1a
Create Date: 2021-10-16 13:45:15.305286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45c8fb782235'
down_revision = 'fc4978528b1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('pasien_ibfk_2', 'pasien', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('pasien_ibfk_2', 'pasien', 'user', ['id_user'], ['id'])
    # ### end Alembic commands ###
