"""empty message

Revision ID: 5b0e1e832e8d
Revises: a793436b3676
Create Date: 2021-10-16 13:36:28.876191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b0e1e832e8d'
down_revision = 'a793436b3676'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'pasien', 'user', ['id_user'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pasien', type_='foreignkey')
    # ### end Alembic commands ###
