"""empty message

Revision ID: 6eab96b714c1
Revises: 5b0e1e832e8d
Create Date: 2021-10-16 13:38:37.368578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6eab96b714c1'
down_revision = '5b0e1e832e8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'pasien', 'user', ['id_user'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pasien', type_='foreignkey')
    # ### end Alembic commands ###
