"""empty message

Revision ID: a793436b3676
Revises: 
Create Date: 2021-10-16 13:34:21.482839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a793436b3676'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pasien', sa.Column('id_user', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'pasien', 'user', ['id_user'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pasien', type_='foreignkey')
    op.drop_column('pasien', 'id_user')
    # ### end Alembic commands ###
