"""empty message

Revision ID: fc4978528b1a
Revises: 1460fda42dbb
Create Date: 2021-10-16 13:42:06.149585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc4978528b1a'
down_revision = '1460fda42dbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pasien', sa.Column('id_user', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'pasien', 'user', ['id_user'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pasien', type_='foreignkey')
    op.drop_column('pasien', 'id_user')
    # ### end Alembic commands ###
